apiVersion: cli.kyverno.io/v1alpha1
kind: Test
metadata:
  name: restrict-external-ips
policies:
  - ../policy.yaml
resources:
  - resources.yaml
results:
  - policy: restrict-external-ips
    rule: check-external-ips
    kind: Service
    resources:
      - good-svc-cluster-ip
    result: pass
  - policy: restrict-external-ips
    rule: check-external-ips
    kind: Service
    resources:
      - bad-svc-external-ips
    result: fail
  - policy: restrict-external-ips
    rule: check-external-ips
    kind: Service
    resources:
      - exempt-system-svc
    result: skip
