apiVersion: cli.kyverno.io/v1alpha1
kind: Test
metadata:
  name: require-requests-limits
policies:
  - ../policy.yaml
resources:
  - resources.yaml
results:
  - policy: require-requests-limits
    rule: require-requests-limits
    kind: Pod
    resources:
      - good-pod
    result: pass
  - policy: require-requests-limits
    rule: require-requests-limits
    kind: Pod
    resources:
      - bad-pod-no-limits
      - bad-pod-init-no-limits
      - bad-pod-no-cpu-limit
    result: fail
  - policy: require-requests-limits
    rule: require-requests-limits
    kind: Pod
    resources:
      - exempt-system-pod
    result: skip
