apiVersion: v1
kind: Pod
metadata:
  name: good-pod
  namespace: backend
spec:
  containers:
    - name: app
      image: nginx:1.29
---
apiVersion: v1
kind: Pod
metadata:
  name: bad-pod
  namespace: default
spec:
  containers:
    - name: app
      image: nginx:1.29
